import DrawerLayoutAndroid from 'react-native-drawer-layout'
import Slider              from 'react-native-slider'
import {
  // top-level API
  createElement,
  findNodeHandle,
  render,
  unmountComponentAtNode,
  // modules
  processColor,
  NativeModules,
  TextPropTypes,
  ViewPropTypes,
  // APIs
  Animated,
  AppRegistry,
  AppState,
  AsyncStorage,
  BackHandler,
  Clipboard,
  Dimensions,
  Easing,
  I18nManager,
  InteractionManager,
  Keyboard,
  Linking,
  NetInfo,
  PanResponder,
  PixelRatio,
  Platform,
  StyleSheet,
  UIManager,
  Vibration,
  // components
  ActivityIndicator,
  ART,
  Button,
  CheckBox,
  Image,
  ImageBackground,
  KeyboardAvoidingView,
  ListView,
  Picker,
  ProgressBar,
  SafeAreaView,
  ScrollView,
  Switch,
  Text,
  TextInput,
  Touchable,
  TouchableHighlight,
  TouchableNativeFeedback,
  TouchableOpacity,
  TouchableWithoutFeedback,
  View,
  VirtualizedList,
  // propTypes
  ColorPropType,
  EdgeInsetsPropType,
  PointPropType
} from 'react-native-web'

import Alert          from 'react-native-web-extended/dist/apis/Alert'
import RefreshControl from 'react-native-web-extended/dist/components/RefreshControl'
import TabBarIOS      from 'react-native-web-extended/dist/components/TabBarIOS'

import FlatList    from 'react-native-web-lists/src/FlatList'
import SectionList from 'react-native-web-lists/src/SectionList'

import Modal     from 'react-native-web-modal'
import StatusBar from 'react-native-web-statusbar'
import WebView   from 'react-native-web-webview'

const AlertIOS = Alert


export {
  // top-level API
  createElement,
  findNodeHandle,
  render,
  unmountComponentAtNode,
  // modules
  processColor,
  NativeModules,
  TextPropTypes,
  ViewPropTypes,
  // APIs
  Alert,
  AlertIOS,
  Animated,
  AppRegistry,
  AppState,
  AsyncStorage,
  BackHandler,
  Clipboard,
  Dimensions,
  Easing,
  I18nManager,
  InteractionManager,
  Keyboard,
  Linking,
  NetInfo,
  PanResponder,
  PixelRatio,
  Platform,
  StyleSheet,
  UIManager,
  Vibration,
  // components
  ActivityIndicator,
  ART,
  Button,
  CheckBox,
  DrawerLayoutAndroid,
  FlatList,
  Image,
  ImageBackground,
  KeyboardAvoidingView,
  ListView,
  Modal,
  Picker,
  ProgressBar,
  RefreshControl,
  SafeAreaView,
  ScrollView,
  SectionList,
  Slider,
  StatusBar,
  Switch,
  TabBarIOS,
  Text,
  TextInput,
  Touchable,
  TouchableHighlight,
  TouchableNativeFeedback,
  TouchableOpacity,
  TouchableWithoutFeedback,
  View,
  VirtualizedList,
  WebView,
  // propTypes
  ColorPropType,
  EdgeInsetsPropType,
  PointPropType
}

export default {
  // top-level API
  createElement,
  findNodeHandle,
  render,
  unmountComponentAtNode,
  // modules
  processColor,
  NativeModules,
  TextPropTypes,
  ViewPropTypes,
  // APIs
  Alert,
  AlertIOS,
  Animated,
  AppRegistry,
  AppState,
  AsyncStorage,
  BackHandler,
  Clipboard,
  Dimensions,
  Easing,
  I18nManager,
  InteractionManager,
  Keyboard,
  Linking,
  NetInfo,
  PanResponder,
  PixelRatio,
  Platform,
  StyleSheet,
  UIManager,
  Vibration,
  // components
  ActivityIndicator,
  ART,
  Button,
  CheckBox,
  DrawerLayoutAndroid,
  FlatList,
  Image,
  ImageBackground,
  KeyboardAvoidingView,
  ListView,
  Modal,
  Picker,
  ProgressBar,
  RefreshControl,
  SafeAreaView,
  ScrollView,
  SectionList,
  Slider,
  StatusBar,
  Switch,
  TabBarIOS,
  Text,
  TextInput,
  Touchable,
  TouchableHighlight,
  TouchableNativeFeedback,
  TouchableOpacity,
  TouchableWithoutFeedback,
  View,
  VirtualizedList,
  WebView,
  // propTypes
  ColorPropType,
  EdgeInsetsPropType,
  PointPropType
}
